create table mediciones (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  temperatura numeric not null,
  humedad numeric not null,
  ubicacion text default 'Puerto La Cruz'
);

-- Habilitar RLS para mayor seguridad
alter table mediciones enable row level security;

-- Permitir lectura pública de los datos
create policy "Permitir lectura publica" on mediciones
  for select using (true);

-- Permitir insercion de nuevas mediciones
create policy "Permitir insercion publica" on mediciones
  for insert with check (true);